//
//  FindTheDifference .swift
//  LeetCode-Swift
//
//  Created by jackma on 2023/3/7.
//  Copyright © 2023 JackMa. All rights reserved.
//

import Foundation

/**
 https://leetcode.com/problems/find-the-difference
 
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.
 
 Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
 */

extension Solution {
    func FindTheDifference(_ s: String, _ t: String) -> Character {
        let aAsciiValue = Character("a").asciiValue!
        
        // String s and t are lowercase, construct an array of 26 lengths
        // The array index(0~25) mean letter(a~z), value mean the appear count of letter in s
        var bitMap = Array(repeating: 0, count: 26)
        for sChar in s {
            if let sCharValue = sChar.asciiValue {
                let index:Int = Int(sCharValue - aAsciiValue)
                bitMap[index] += 1
            }
        }
        
        for tChar in t {
            if let tCharValue = tChar.asciiValue {
                let index = Int(tCharValue - aAsciiValue)
                if bitMap[index] != 0 {
                    // tChar appearr in the string s
                    bitMap[index] -= 1
                } else {
                    return tChar
                }
            }
        }
        
        return Character(" ")
    }
}
